### ISSUE TITLE
Nicer issue link embedded visualization

### ISSUE THREAD

**Issue by sirnicolaz** [deeecent/propcorn#1]
Currently the github link is displayed as raw text. It would give a more "integrated" feeling to render it as a Github issue like it is inside Github itself, for instance by showing the title of the issue, the author and the "closed/open" badge next to it.

I am willing to fund it with 0.01 ETH. Please create your proposal through the [bounty link](https://propcorn.deeecent.website/#/?link=https://github.com/deeecent/propcorn/issues/1&fund=0.01) if interested

**Comment by AnupamGaur** [comment]
Hi @sirnicolaz I would like to work on this.
![image](https://github.com/user-attachments/assets/d5a7265f-abf0-4db8-af88-3214a7378fe0)

The submit button was not working, so I have generated my proposal through URL. 
Does this work?
https://propcorn.deeecent.website/#/proposals/0xc6646fF93ba0fD33Bf720fF9208207aa4cae9B68/0

**Comment by AnupamGaur** [comment]
How does the initial look look like

https://github.com/user-attachments/assets/163f5c13-ca2e-4bff-a0f7-e61ce1903679

**Comment by vrde** [comment]
Hi @AnupamGaur thanks for your comment, how do you pull the data from GitHub?

**Comment by AnupamGaur** [comment]
Hi @vrde I have used GIthub's REST API @api.github.com to fetch the data.
I have completed the task.I am going ahead and making a pull request. Suggest changes if any!

**Comment by sirnicolaz** [comment]
We are going to close this PR as we have redesigned the website in its entirety.

Also next time, please make sure you first create a proposal and wait for it to be funded @AnupamGaur , that's the moment where you are sure you can start working on a proposal. Thanks anyway for your contribution.
