### ISSUE TITLE
Add a light theme to the dapp

### ISSUE THREAD

**Issue by vrde** [deeecent/propcorn#2]
Our current website lacks support for multiple modes. This task is to implement both light and dark modes, with the website automatically selecting the appropriate mode based on the user’s system settings.

To participate in this bounty, [create a new proposal](https://propcorn.deeecent.website/#/?link=https://github.com/deeecent/propcorn/issues/2&fund=0.02) and post it here in the comments.

**Comment by TimDaub** [comment]
https://propcorn.deeecent.website/#/proposals/0xee324c588ceF1BF1c1360883E4318834af66366d/0
