### ISSUE TITLE
Make a logo for this project

### ISSUE THREAD

**Issue by vrde** [deeecent/propcorn#4]
There is no logo for this protocol. Would be nice something related to 🍿.

To participate in this bounty, [create a new proposal](https://propcorn.deeecent.website/#/?link=https://github.com/deeecent/propcorn/issues/3&fund=0.025) and post it here in the comments, add a description of your idea.

**Comment by aliraza556** [comment]
@vrde Please assign me?

**Comment by vrde** [comment]
> @vrde Please assign me?

read the instructions

**Comment by sirnicolaz** [comment]
done with #25
